packages:
  - packages/*
  - apps/*
  - tooling/*
  - e2e-tests
ignoredBuiltDependencies:
  - esbuild
  - keccak
  - secp256k1
  - utf-8-validate
onlyBuiltDependencies:
  - bigint-buffer
  - bufferutil
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - react
  - "@blastctrl/*"
  - "@types/react"
  - "@tanstack/react-query"
  - "@tanstack/react-query-devtools"
