packages:
  - packages/*
  - apps/*
  - e2e-tests
blockExoticSubdeps: true
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - react
  - "@blastctrl/*"
  - "@types/react"
  - next
  - "@next/*"
peerDependencyRules:
  allowedVersions:
    "@solana/kit": "2 || 5"
overrides:
  "elliptic@<=6.6.0": "^6.6.1"
  "protobufjs@<7.5.5": "^7.5.5"
  "undici@<6.24.0": "^6.24.0"
  "ws@<7.5.10": "^7.5.10"
  "secp256k1@5.0.0": "^5.0.1"
  "shell-quote@<1.8.4": "^1.8.4"
allowBuilds:
  bigint-buffer: true
  bufferutil: true
  sharp: true
  esbuild: true
  keccak: false
  secp256k1: false
  utf-8-validate: false
  "@stellar/stellar-sdk": false
  blake-hash: false
  protobufjs: false
  tiny-secp256k1: false
  unrs-resolver: false
  usb: false
