packages:
  - packages/*
  - apps/*
  - tooling/*
  - e2e-tests
ignoredBuiltDependencies:
  - esbuild
  - keccak
  - secp256k1
  - utf-8-validate
onlyBuiltDependencies:
  - bigint-buffer
  - bufferutil
minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - react
  - "@blastctrl/*"
  - "@types/react"
  - "@tanstack/react-query"
  - "@tanstack/react-query-devtools"
patchedDependencies:
  "@ardrive/turbo-sdk@1.41.1": "patches/@ardrive__turbo-sdk@1.41.1.patch"
peerDependencyRules:
  allowedVersions:
    "@solana/kit": "2 || 5"
overrides:
  "elliptic@<=6.6.0": "^6.6.1"
  "protobufjs@<7.5.5": "^7.5.5"
  "undici@<6.24.0": "^6.24.0"
  "ws@<7.5.10": "^7.5.10"
  "secp256k1@5.0.0": "^5.0.1"
