name: Gasless Swap Periodic Test

on:
  schedule:
    # Runs every Thursday at 20:00 UTC
    - cron: "0 20 * * 4"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./e2e-tests

jobs:
  test_gasless_swap:
    runs-on: ubuntu-latest
    env:
      SWAPPER_PRIVATE_KEY: ${{ secrets.SWAPPER_PRIVATE_KEY }}
      FUNDER_PRIVATE_KEY: ${{ secrets.FUNDER_PRIVATE_KEY }}
      RPC_URL: ${{ secrets.RPC_URL }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      PW_CHROMIUM_ATTACH_TO_OTHER: ${{ secrets.PW_CHROMIUM_ATTACH_TO_OTHER }}
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install dependencies
        run: |
          pnpm install
          pnpm exec playwright install --with-deps chromium
      - name: Run the Playwright Test
        run: pnpm exec playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./playwright-report/
          retention-days: 10
